### ISSUE TITLE
Application Error,  I want to fix it.

### ISSUE THREAD

**Issue by Firstmeowwhite** [IntelOrca/PVZTools#2]
![Untitled](https://user-images.githubusercontent.com/57336625/77503647-ba68d580-6e90-11ea-9d40-a28cda9814f2.png)

**Comment by xparadoxical** [comment]
@Firstmeowwhite should be fixed in my fork: https://github.com/xparadoxical/PVZTools

**Comment by IntelOrca** [comment]
@xparadoxical I am happy to accept a pull request
